# Generated by Django 5.0.1 on 2024-02-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("localId", models.IntegerField(verbose_name="本地ID")),
                ("talkerId", models.IntegerField(verbose_name="对话者ID")),
                ("type", models.IntegerField(verbose_name="消息类型")),
                ("subType", models.IntegerField(default=0, verbose_name="子类型")),
                ("isSender", models.BooleanField(default=False, verbose_name="是否为发送者")),
                ("createTime", models.BigIntegerField(verbose_name="创建时间")),
                (
                    "status",
                    models.IntegerField(blank=True, null=True, verbose_name="状态"),
                ),
                (
                    "strContent",
                    models.TextField(blank=True, null=True, verbose_name="字符串内容"),
                ),
                ("strTime", models.CharField(max_length=20, verbose_name="字符串时间")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "nickName",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="昵称"
                    ),
                ),
                (
                    "sender",
                    models.IntegerField(blank=True, null=True, verbose_name="发送者"),
                ),
            ],
            options={
                "verbose_name": "聊天记录",
                "verbose_name_plural": "聊天记录",
            },
        ),
    ]
