# Generated by Django 5.0.1 on 2024-02-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatrecord",
            name="createTime",
            field=models.CharField(max_length=255, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="chatrecord",
            name="isSender",
            field=models.CharField(
                default=False, max_length=255, verbose_name="是否为发送者"
            ),
        ),
        migrations.AlterField(
            model_name="chatrecord",
            name="localId",
            field=models.CharField(max_length=255, verbose_name="本地ID"),
        ),
        migrations.AlterField(
            model_name="chatrecord",
            name="status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="chatrecord",
            name="subType",
            field=models.CharField(default=0, max_length=255, verbose_name="子类型"),
        ),
        migrations.AlterField(
            model_name="chatrecord",
            name="talkerId",
            field=models.CharField(max_length=255, verbose_name="对话者ID"),
        ),
        migrations.AlterField(
            model_name="chatrecord",
            name="type",
            field=models.CharField(max_length=255, verbose_name="消息类型"),
        ),
    ]
